services:
  facefusion-worker:
    build: .
    image: facefusion-api:latest
    ports:
      - "8001:8000"
    volumes:
      - ./.assets:/app/.assets
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]